"""
Generates one real HTML page per project, plus the sitemap.

    python tools/generate_project_pages.py

Why this exists
---------------
Every project used to live at the same single URL, injected into the carousel
by JavaScript. Nobody could find "Rostam & Sohrab" by searching for it, nobody
could link to it, and a search engine had one page to index for a body of work
that is actually a dozen separate pieces. This turns each one into an address:

    https://sayfit.ir/work/sculpture/rostam-and-sohrab/

The carousel on the home page is untouched. It stays exactly as it is - these
pages are in addition to it, not instead of it, and the carousel now links into
them.

What it reads
-------------
    data/projects.json    generated by update_projects.py - the source of truth
    i18n/en.json          for the page chrome (nav, footer)
    i18n/fa.json

What it writes
--------------
    work/<category>/<slug>/index.html      one per project
    work/<category>/index.html             one per category, listing its projects
    sitemap.xml                            every page, with hreflang alternates

Safe to run as often as you like: it only ever writes those paths, and it
removes pages whose project has disappeared from projects.json.

Run it AFTER update_projects.py, and upload the generated work/ folder along
with data/projects.json. See docs/PROJECT_PAGES.md.
"""

import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "projects.json"
OUT_ROOT = ROOT / "work"
SITEMAP = ROOT / "sitemap.xml"

SITE_URL = "https://sayfit.ir"

# Category key -> the anchor it belongs to on the home page, and the i18n key
# for its visible name. The keys are folder names and must not be renamed; see
# docs/MEDIA.md.
CATEGORIES = {
    "sculpture": {"anchor": "sculpture", "i18n": "work.sculpture", "en": "Sculpture"},
    "tailor-made-glasses": {"anchor": "tailor-made-glasses", "i18n": "work.glasses", "en": "Tailor made glasses"},
    "logo-design": {"anchor": "logo-design", "i18n": "work.identity", "en": "Visual identity"},
}


# --------------------------------------------------------------------------
# Slugs
#
# The URL slug comes from the project's FOLDER name, not its title, because the
# folder name is what update_projects.py derives everything else from and it is
# the one thing guaranteed to be stable.
#
# js/modules/slug.js implements exactly this, so the carousel can work out a
# project's URL in the browser without the slug having to be stored anywhere.
# If you change the rule here, change it there too.
# --------------------------------------------------------------------------

def slugify(name):
    slug = name.lower().replace("&", "-and-")
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def folder_from_media(project):
    """Pull the source folder name out of the first media path."""
    for item in project.get("media", []):
        match = re.search(r"projects/work/[^/]+/([^/]+)/", item.get("src", ""))
        if match:
            return match.group(1)
    return project.get("title", "untitled")


# --------------------------------------------------------------------------
# Media URLs
#
# projects.json stores media paths RELATIVE to the asset repo; the browser
# resolves them against `cdnBase` at runtime. A generated page cannot do that -
# its og:image is read by Telegram and Google, which are not running our
# JavaScript - so the absolute URL has to be baked in here.
# --------------------------------------------------------------------------

def resolve_media(src, cdn_base):
    if not src:
        return ""
    if re.match(r"^[a-z][a-z\d+\-.]*:", src, re.I) or src.startswith("//"):
        return src
    base = cdn_base if cdn_base.endswith("/") else cdn_base + "/"
    return base + src.lstrip("/")


def escape(text):
    return (
        str(text or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def summarise(project, category_name):
    """The meta description. Falls back to something useful if desc is blank."""
    desc = (project.get("desc") or "").strip()
    if desc:
        return desc
    year = project.get("year")
    year_part = f", {year}" if year else ""
    return f"{project.get('title', '')} — {category_name.lower()} by Mehdi Seyfi{year_part}. Sayfit Studio."


# --------------------------------------------------------------------------
# Templates
# --------------------------------------------------------------------------

def head_common(depth):
    up = "../" * depth
    return f"""  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
  <meta name="theme-color" content="#ffffff">
  <meta name="color-scheme" content="light">
  <meta name="author" content="Mehdi Seyfi">
  <link rel="icon" type="image/svg+xml" href="{up}image/favicon.svg">
  <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
  <link rel="stylesheet" href="{up}css/style.css">"""


def site_header(depth):
    up = "../" * depth
    return f"""  <header class="sticky-nav" id="stickyNav">
    <div class="sticky-left">
      <button class="hamburger" id="hamburgerBtn" type="button"
              data-i18n-attr="aria-label:nav.menuToggle"
              aria-label="Toggle navigation menu" aria-controls="navCenter" aria-expanded="false">
        <span></span><span></span><span></span>
      </button>

      <nav class="sticky-links" id="navCenter" aria-label="Pinned navigation">
        <a href="{up}" data-i18n="nav.home">Home</a>
        <a href="{up}#sculpture" data-i18n="work.sculpture">Sculpture</a>
        <a href="{up}#tailor-made-glasses" data-i18n="work.glasses">Tailor made glasses</a>
        <a href="{up}#logo-design" data-i18n="work.identity">Visual identity</a>
        <a href="{up}#apps" data-i18n="nav.apps">App</a>
        <a href="{up}#about" data-i18n="nav.about">About</a>
        <a href="{up}#contact" data-i18n="nav.contact">Contact</a>
      </nav>
    </div>

    <div class="sticky-right">
      <button class="lang-switch" id="langSwitch" type="button"
              data-i18n="nav.languageToggle"
              data-i18n-attr="aria-label:nav.languageToggleLabel"
              aria-label="Switch language to Persian">فارسی</button>
      <a class="sticky-brand" href="{up}" data-i18n="brand.name">Sayfit</a>
    </div>
  </header>"""


def site_footer():
    return """  <footer class="site-footer"><span data-i18n="footer.copyright">© 2026 Sayfit Studio.</span></footer>"""


def modal_markup():
    """The same lightbox the home page uses, so gallery images open in it."""
    return """  <div class="modal-backdrop" id="projectModal" aria-hidden="true">
    <div class="modal-content" role="dialog" aria-modal="true" aria-labelledby="modalTitle">
      <button class="close-modal" id="closeModal" type="button" data-i18n-attr="aria-label:modal.close" aria-label="Close">&times;</button>
      <button class="modal-nav modal-prev" id="modalPrev" type="button" data-i18n-attr="aria-label:modal.prev" aria-label="Previous media">&#10094;</button>
      <button class="modal-nav modal-next" id="modalNext" type="button" data-i18n-attr="aria-label:modal.next" aria-label="Next media">&#10095;</button>
      <span class="modal-counter" id="modalCounter"></span>
      <div class="modal-body">
        <span class="modal-year" id="modalYear"></span>
        <h2 class="modal-title" id="modalTitle"></h2>
        <div class="modal-main-media" id="modalMainMedia"></div>
        <div class="modal-thumbnails" id="modalThumbnails"></div>
        <p class="modal-desc" id="modalDesc"></p>
      </div>
    </div>
  </div>"""


def render_project_page(project, category_key, slug, siblings, index):
    meta = CATEGORIES[category_key]
    category_name = meta["en"]
    title = project.get("title", "")
    year = project.get("year", "")
    desc = summarise(project, category_name)
    media = project.get("media", [])
    cover = media[0]["src"] if media else ""

    url = f"{SITE_URL}/work/{category_key}/{slug}/"
    page_title = f"{title}{f' ({year})' if year else ''} — {category_name} by Mehdi Seyfi | Sayfit Studio"

    previous_project = siblings[index - 1] if index > 0 else None
    next_project = siblings[index + 1] if index < len(siblings) - 1 else None

    def sibling_link(entry, key, label_key, fallback):
        if not entry:
            return ""
        return (
            f'<a class="project-page-step" href="../{entry["slug"]}/">'
            f'<span class="project-page-step-label" data-i18n="{label_key}">{fallback}</span>'
            f'<span class="project-page-step-title">{escape(entry["title"])}</span></a>'
        )

    gallery = "\n".join(
        f"""        <figure class="project-page-figure">
          <button class="project-page-shot" type="button" data-index="{i}"
                  data-i18n-attr="aria-label:project.openImage" aria-label="Open image">
            {'<video src="' + escape(item["src"]) + '" muted loop playsinline></video>'
             if item.get("type") == "video" else
             '<img src="' + escape(item["src"]) + '" alt="' + escape(title) + '" loading="' + ("eager" if i == 0 else "lazy") + '" decoding="async">'}
          </button>
        </figure>"""
        for i, item in enumerate(media)
    )

    # VisualArtwork is the closest schema.org type for a sculpture. The
    # BreadcrumbList is what produces the Home > Work > Sculpture trail under
    # the result rather than a bare URL.
    structured = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "VisualArtwork",
                "@id": url + "#artwork",
                "name": title,
                "url": url,
                "image": [item["src"] for item in media[:8]],
                "description": desc,
                "artform": category_name,
                "creator": {"@type": "Person", "@id": f"{SITE_URL}/#person", "name": "Mehdi Seyfi"},
                "isPartOf": {"@type": "CollectionPage", "@id": f"{SITE_URL}/work/{category_key}/"},
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE_URL + "/"},
                    {"@type": "ListItem", "position": 2, "name": category_name, "item": f"{SITE_URL}/work/{category_key}/"},
                    {"@type": "ListItem", "position": 3, "name": title},
                ],
            },
        ],
    }
    if year:
        structured["@graph"][0]["dateCreated"] = str(year)

    return f"""<!DOCTYPE html>
<!--
  GENERATED FILE - do not edit by hand.

  Written by tools/generate_project_pages.py from data/projects.json.
  Anything you change here is lost the next time that script runs. To change
  the words, edit the project's title/year/desc in data/projects.json; to
  change the layout, edit the template in the script.
-->
<html lang="en" dir="ltr">
<head>
{head_common(3)}

  <title>{escape(page_title)}</title>
  <meta name="description" content="{escape(desc)}">

  <link rel="canonical" href="{url}">
  <link rel="alternate" hreflang="en" href="{url}">
  <link rel="alternate" hreflang="fa" href="{url}?lang=fa">
  <link rel="alternate" hreflang="x-default" href="{url}">

  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Sayfit Studio">
  <meta property="og:url" content="{url}">
  <meta property="og:title" content="{escape(title)} — {escape(category_name)} by Mehdi Seyfi">
  <meta property="og:description" content="{escape(desc)}">
  <meta property="og:image" content="{escape(cover)}">
  <meta property="og:image:alt" content="{escape(title)}">
  <meta property="og:locale" content="en_US">
  <meta property="og:locale:alternate" content="fa_IR">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape(title)} — {escape(category_name)}">
  <meta name="twitter:description" content="{escape(desc)}">
  <meta name="twitter:image" content="{escape(cover)}">

  <script type="application/ld+json">
{json.dumps(structured, ensure_ascii=False, indent=2)}
  </script>
</head>

<body class="project-page" data-i18n-pending>
  <noscript>
    <style>
      body[data-i18n-pending] main,
      body[data-i18n-pending] .sticky-nav,
      body[data-i18n-pending] .site-footer {{ visibility: visible; }}
    </style>
  </noscript>

{site_header(3)}

  <main class="project-page-main">
    <nav class="project-page-crumbs" aria-label="Breadcrumb">
      <a href="../../../" data-i18n="project.breadcrumbHome">Home</a>
      <span aria-hidden="true">/</span>
      <a href="../" data-i18n="{meta['i18n']}">{escape(category_name)}</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page">{escape(title)}</span>
    </nav>

    <header class="project-page-head">
      <p class="project-page-year">{escape(year)}</p>
      <h1 class="project-page-title">{escape(title)}</h1>
      <p class="project-page-desc">{escape(project.get('desc', ''))}</p>
      <p class="project-page-count">{len(media)} <span data-i18n="project.imageCount">images</span></p>
    </header>

    <section class="project-page-gallery" aria-label="Gallery">
{gallery}
    </section>

    <nav class="project-page-steps" aria-label="Other projects">
      {sibling_link(previous_project, 'prev', 'project.previous', 'Previous project')}
      {sibling_link(next_project, 'next', 'project.next', 'Next project')}
    </nav>

    <p class="project-page-back">
      <a href="../"><span data-i18n="project.backToCategory">Back to</span>
      <span data-i18n="{meta['i18n']}">{escape(category_name)}</span></a>
    </p>
  </main>

{site_footer()}
{modal_markup()}

  <script type="module" src="../../../js/project-page.js"></script>
</body>
</html>
"""


def render_category_page(category_key, projects):
    meta = CATEGORIES[category_key]
    category_name = meta["en"]
    url = f"{SITE_URL}/work/{category_key}/"
    desc = f"{category_name} by Mehdi Seyfi — {len(projects)} projects from Sayfit Studio."

    cards = "\n".join(
        f"""        <li class="project-card">
          <a class="project-card-link" href="{entry['slug']}/">
            <span class="project-card-shot">
              <img src="{escape(entry['cover'])}" alt="{escape(entry['title'])}" loading="lazy" decoding="async">
            </span>
            <span class="project-card-body">
              <span class="project-card-year">{escape(entry['year'])}</span>
              <span class="project-card-title">{escape(entry['title'])}</span>
            </span>
          </a>
        </li>"""
        for entry in projects
    )

    structured = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "@id": url,
        "name": category_name,
        "url": url,
        "description": desc,
        "hasPart": [
            {"@type": "VisualArtwork", "name": e["title"], "url": f"{url}{e['slug']}/"}
            for e in projects
        ],
    }

    return f"""<!DOCTYPE html>
<!-- GENERATED FILE - written by tools/generate_project_pages.py. Do not edit. -->
<html lang="en" dir="ltr">
<head>
{head_common(2)}

  <title>{escape(category_name)} — Mehdi Seyfi | Sayfit Studio</title>
  <meta name="description" content="{escape(desc)}">

  <link rel="canonical" href="{url}">
  <link rel="alternate" hreflang="en" href="{url}">
  <link rel="alternate" hreflang="fa" href="{url}?lang=fa">
  <link rel="alternate" hreflang="x-default" href="{url}">

  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Sayfit Studio">
  <meta property="og:url" content="{url}">
  <meta property="og:title" content="{escape(category_name)} — Mehdi Seyfi">
  <meta property="og:description" content="{escape(desc)}">
  <meta property="og:image" content="{escape(projects[0]['cover']) if projects else ''}">

  <script type="application/ld+json">
{json.dumps(structured, ensure_ascii=False, indent=2)}
  </script>
</head>

<body class="project-page" data-i18n-pending>
  <noscript>
    <style>
      body[data-i18n-pending] main,
      body[data-i18n-pending] .sticky-nav,
      body[data-i18n-pending] .site-footer {{ visibility: visible; }}
    </style>
  </noscript>

{site_header(2)}

  <main class="project-page-main">
    <nav class="project-page-crumbs" aria-label="Breadcrumb">
      <a href="../../" data-i18n="project.breadcrumbHome">Home</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page" data-i18n="{meta['i18n']}">{escape(category_name)}</span>
    </nav>

    <header class="project-page-head">
      <h1 class="project-page-title" data-i18n="sections.{'sculpture' if category_key == 'sculpture' else ('glasses' if category_key == 'tailor-made-glasses' else 'identity')}.title">{escape(category_name)}</h1>
      <p class="project-page-desc" data-i18n="sections.{'sculpture' if category_key == 'sculpture' else ('glasses' if category_key == 'tailor-made-glasses' else 'identity')}.intro"></p>
    </header>

    <ul class="project-grid">
{cards}
    </ul>
  </main>

{site_footer()}

  <script type="module" src="../../js/project-page.js"></script>
</body>
</html>
"""


def render_sitemap(pages):
    entries = "\n".join(
        f"""  <url>
    <loc>{loc}</loc>
    <xhtml:link rel="alternate" hreflang="en" href="{loc}"/>
    <xhtml:link rel="alternate" hreflang="fa" href="{loc}?lang=fa"/>
    <xhtml:link rel="alternate" hreflang="x-default" href="{loc}"/>
  </url>"""
        for loc in pages
    )

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED FILE - written by tools/generate_project_pages.py.
  Re-run that script after adding or removing a project; do not edit by hand.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
{entries}
  <url><loc>{SITE_URL}/customer/</loc></url>
</urlset>
"""


# --------------------------------------------------------------------------

def main():
    if not DATA.exists():
        sys.exit(f"{DATA} not found. Run update_projects.py first.")

    data = json.loads(DATA.read_text(encoding="utf-8"))
    groups = data.get("projects", {})
    cdn_base = data.get("cdnBase") or data.get("baseUrl") or ""
    if not cdn_base:
        sys.exit("projects.json has no cdnBase - run update_projects.py first.")

    written = []
    sitemap_pages = [f"{SITE_URL}/"]
    live_dirs = set()

    for category_key, projects in groups.items():
        if category_key not in CATEGORIES:
            print(f"  ! skipping unknown category '{category_key}'")
            continue
        if not projects:
            continue

        entries = []
        for project in projects:
            slug = slugify(folder_from_media(project))
            # Bake the CDN base in - see resolve_media above.
            resolved = dict(project)
            resolved["media"] = [
                {**item, "src": resolve_media(item.get("src", ""), cdn_base)}
                for item in project.get("media", [])
            ]
            entries.append({
                "slug": slug,
                "title": project.get("title", ""),
                "year": project.get("year", ""),
                "cover": resolved["media"][0]["src"] if resolved["media"] else "",
                "project": resolved,
            })

        category_dir = OUT_ROOT / category_key
        category_dir.mkdir(parents=True, exist_ok=True)
        live_dirs.add(category_dir)

        (category_dir / "index.html").write_text(
            render_category_page(category_key, entries), encoding="utf-8"
        )
        sitemap_pages.append(f"{SITE_URL}/work/{category_key}/")
        written.append(f"work/{category_key}/index.html")

        for index, entry in enumerate(entries):
            page_dir = category_dir / entry["slug"]
            page_dir.mkdir(parents=True, exist_ok=True)
            live_dirs.add(page_dir)
            (page_dir / "index.html").write_text(
                render_project_page(entry["project"], category_key, entry["slug"], entries, index),
                encoding="utf-8",
            )
            sitemap_pages.append(f"{SITE_URL}/work/{category_key}/{entry['slug']}/")
            written.append(f"work/{category_key}/{entry['slug']}/index.html")

    # Remove pages for projects that no longer exist, so a renamed folder does
    # not leave a stale URL behind for search engines to keep indexing.
    removed = []
    if OUT_ROOT.exists():
        for path in sorted(OUT_ROOT.glob("*/*")):
            if path.is_dir() and path not in live_dirs:
                shutil.rmtree(path)
                removed.append(str(path.relative_to(ROOT)))
        for path in sorted(OUT_ROOT.glob("*")):
            if path.is_dir() and path not in live_dirs and not any(path.iterdir()):
                path.rmdir()
                removed.append(str(path.relative_to(ROOT)))

    SITEMAP.write_text(render_sitemap(sitemap_pages), encoding="utf-8")

    print(f"Wrote {len(written)} pages:")
    for path in written:
        print(f"  {path}")
    if removed:
        print("Removed stale:")
        for path in removed:
            print(f"  {path}")
    # Duplicate meta descriptions are a real ranking problem: search engines
    # treat near-identical pages as thin content and pick one of them to show.
    # This is a content issue, not a code one, so warn rather than invent text.
    seen = {}
    for cat_projects in groups.values():
        for item in cat_projects:
            desc = (item.get("desc") or "").strip()
            if desc:
                seen.setdefault(desc, []).append(item.get("title", "?"))
    duplicates = {d: t for d, t in seen.items() if len(t) > 1}
    if duplicates:
        print("")
        print("  ! Several projects share the same description, so their pages")
        print("    carry identical meta descriptions and compete with each other.")
        print("    Give each its own desc in data/projects.json - it is the")
        print("    sentence a search result actually shows:")
        for dup_desc, titles in duplicates.items():
            print("      " + ", ".join(titles))
            print('        "' + dup_desc[:64] + '"')

    print(f"\nsitemap.xml now lists {len(sitemap_pages) + 1} URLs.")
    print("\nUpload work/ and sitemap.xml to the web host along with data/projects.json.")


if __name__ == "__main__":
    main()
