/**
 * Loads data/projects.json and turns the relative media paths inside it into
 * absolute jsDelivr URLs.
 *
 * data/projects.json is generated by update_projects.py - do not hand-edit its
 * `media` arrays or its `cdnBase`. Editing a project's year, title or desc is
 * fine and survives regeneration.
 */

import { PROJECT_DATA_URL, DEFAULT_CDN_BASE } from './config.js';

function isAbsoluteUrl(src) {
  return /^[a-z][a-z\d+\-.]*:/i.test(src) || src.startsWith('//');
}

function ensureTrailingSlash(value) {
  return value.endsWith('/') ? value : `${value}/`;
}

function resolveMediaSrc(src, baseUrl) {
  if (!src || isAbsoluteUrl(src)) return src || '';
  return `${ensureTrailingSlash(baseUrl)}${src.replace(/^\/+/, '')}`;
}

function normalize(rawData) {
  const baseUrl = rawData.cdnBase || rawData.baseUrl || DEFAULT_CDN_BASE;
  const groups = rawData.projects || {};

  return Object.fromEntries(
    Object.entries(groups).map(([key, projects]) => [
      key,
      (Array.isArray(projects) ? projects : []).map((project) => ({
        ...project,
        media: (project.media || []).map((item) => ({
          ...item,
          src: resolveMediaSrc(item.src, baseUrl)
        }))
      }))
    ])
  );
}

/**
 * @returns {Promise<Record<string, Array>>} keyed by category
 *   (`sculpture`, `tailor-made-glasses`, `logo-design`). A category with no
 *   photographs yet is simply absent - the slider renders its empty state.
 */
export async function loadProjectData() {
  const response = await fetch(PROJECT_DATA_URL);
  if (!response.ok) throw new Error(`HTTP ${response.status}`);

  const data = await response.json();
  if (!data || typeof data !== 'object') throw new Error('Invalid data format');

  return normalize(data);
}
